<a href="https://colab.research.google.com/github/oliveralbrecht94/ATDIT2/blob/master/Task%20B.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Import of needed classes**

In [0]:
import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.manifold import TSNE
from scipy import stats
import scipy.spatial.distance


# Load MNIST DATASET

In [0]:
# load MNIST in mnistdataset
mnistdataset = tf.keras.datasets.mnist.load_data()[0]
# load first dimension (digits/images) in digitsand second dimension (labels) in labels
digits, labels = mnistdataset [0], mnistdataset [1]

In [0]:
# load MNIST in testdataset
testdataset = tf.keras.datasets.mnist.load_data()[1]
# load first dimension (digits) in test_digits and second dimension (labels) in test_labels
test_digits, test_labels = testdataset[0], testdataset[1]

# Preparing Dataset

In [0]:
# save amount of digits (from digits) in n_digits
n_digits = digits.shape[0] 
# save amount of digitis (from test_digits) in n_test
n_test = test_digits.shape[0] 

In [0]:
# calculation of full dimension of each image 28*28
amount_pixels = digits.shape[1] * digits.shape[2]

In [0]:
# Transform to 1D vector from each matrix with the pixels of an image in order to calculate distances.
digits = digits.reshape([n_digits, amount_pixels])
test_digits = test_digits.reshape([n_test, amount_pixels])

In [111]:
# see the result
digits.shape

(60000, 784)

In [0]:
# setting an index of 50.0000 between 0 and n_digits (60.000) 
index = np.random.randint(n_digits, size = 50000) 
# set up of samples 
digits_sample = digits[index]
labels_sample = labels[index]

In [0]:
# how much data should be consider? Size = 10 -> 10 numbers of the vector
size_test_sample = 10 
index = np.random.randint(n_test, size = size_test_sample)
test_digits_sample = test_digits[index]
test_labels_sample = test_labels[index]

# Calculating Distances

In [0]:
# setting up the k value 
# k = 2 
k = 4
# k = 8 
# calculating the distance between each vector in dependency of k and save it in an arra
distances = scipy.spatial.distance.cdist(digits_sample, test_digits_sample, metric='euclid')
# calculates the next k points around the vector
index_nearest = np.argpartition(distances, k, axis = 0)[:k] 


In [115]:
# saves the neighbors of the vector in dependency of k
knn_neighbors = labels_sample[index_nearest] 
# show the neighbors
print(knn_neighbors)

[[2 4 0 6 6 9 0 5 5 0]
 [2 4 0 6 5 9 0 5 5 0]
 [2 4 0 6 6 9 0 5 5 0]
 [2 4 0 6 5 9 0 5 5 0]]


In [116]:
# is looking for the most frequent value in the array/vector
knn_result = stats.mode(knn_neighbors)[0]
knn_result = knn_result[0]
# shows the most frequent value
knn_result

array([2, 4, 0, 6, 5, 9, 0, 5, 5, 0], dtype=uint8)

# Get the errorrate

In [0]:
errors = 0
# compares the two arrays and is looking for matches of the values? Right = true / Wrong = false
error_rate_matrix = (test_labels_sample == knn_result)
for b in error_rate_matrix:
    if b == False:
        errors += 1

In [124]:
# Calculation of the error rate
_rate = (errors / size_test_sample) * 100. 
print("Error rate is: " +str(_rate) + " %")

Error rate is: 10.0 %
