<a href="https://colab.research.google.com/github/oliveralbrecht94/ATDIT2/blob/master/Task%20B.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Import of needed classes**

In [0]:
import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.manifold import TSNE
from scipy import stats
import scipy.spatial.distance


# Load MNIST DATASET

In [0]:
# load MNIST in mnistdataset
mnistdataset = tf.keras.datasets.mnist.load_data()[0]
# load first dimension (digits/images) in digitsand second dimension (labels) in labels
digits, labels = mnistdataset [0], mnistdataset [1]

In [0]:
# load MNIST in testdataset
testdataset = tf.keras.datasets.mnist.load_data()[1]
# load first dimension (digits) in test_digits and second dimension (labels) in test_labels
test_digits, test_labels = testdataset[0], testdataset[1]

# Preparing Dataset

In [0]:
# save amount of digits (from digits) in n_digits
n_digits = digits.shape[0] 
# save amount of digitis (from test_digits) in n_test
n_test = test_digits.shape[0] 

In [0]:
# calculation of full dimension of each image 28*28
amount_pixels = digits.shape[1] * digits.shape[2]

In [0]:
# Transform to 1D vector from each matrix with the pixels of an image in order to calculate distances.
digits = digits.reshape([n_digits, amount_pixels])
test_digits = test_digits.reshape([n_test, amount_pixels])

In [17]:
# see the result
digits.shape

(60000, 784)

In [0]:
# setting an index of 50.0000 between 0 and n_digits (60.000) 
index = np.random.randint(n_digits, size = 50000) 
# set up of samples 
digits_sample = digits[index]
labels_sample = labels[index]

In [0]:
# how much data should be consider? Size = 1000 -> 1000 numbers of the vector // it is faster!
size_test_sample = 1000 
index = np.random.randint(n_test, size = size_test_sample)
test_digits_sample = test_digits[index]
test_labels_sample = test_labels[index]

# Calculating Distances

In [0]:
# setting up the k value 
# k = 2 
k = 4
# k = 8 
# calculating the distance between each vector in dependency of k and save it in an arra
distances = scipy.spatial.distance.cdist(digits_sample, test_digits_sample, metric='euclid')
# calculates the next k points around the vector
index_nearest = np.argpartition(distances, k, axis = 0)[:k] 


In [21]:
# saves the neighbors of the vector in dependency of k
knn_neighbors = labels_sample[index_nearest] 
# show the neighbors
print(knn_neighbors)

[[5 2 3 ... 7 9 9]
 [5 2 3 ... 7 9 9]
 [6 2 3 ... 7 9 9]
 [6 2 5 ... 7 9 9]]


In [22]:
# is looking for the most frequent value in the array/vector
knn_result = stats.mode(knn_neighbors)[0]
knn_result = knn_result[0]
# shows the most frequent value
knn_result

array([5, 2, 3, 5, 5, 9, 3, 5, 0, 4, 1, 7, 6, 6, 1, 0, 2, 0, 3, 9, 4, 7,
       2, 2, 0, 3, 3, 8, 0, 3, 6, 3, 0, 6, 8, 3, 9, 0, 1, 6, 4, 2, 9, 9,
       7, 2, 0, 1, 9, 6, 1, 0, 1, 8, 2, 0, 1, 2, 0, 3, 4, 3, 2, 2, 4, 1,
       7, 3, 5, 7, 3, 5, 8, 8, 8, 7, 8, 1, 2, 1, 0, 4, 7, 9, 9, 6, 3, 1,
       0, 8, 0, 6, 8, 2, 7, 4, 3, 9, 0, 3, 8, 6, 0, 7, 7, 0, 3, 4, 0, 7,
       5, 1, 8, 1, 6, 5, 0, 8, 2, 9, 7, 1, 2, 7, 0, 7, 5, 7, 2, 7, 4, 0,
       3, 5, 2, 1, 7, 4, 0, 2, 2, 9, 4, 4, 1, 7, 2, 3, 4, 1, 6, 6, 2, 3,
       7, 1, 5, 5, 5, 3, 1, 3, 2, 7, 3, 7, 8, 1, 3, 1, 2, 2, 2, 4, 7, 4,
       9, 0, 9, 7, 3, 5, 9, 2, 2, 3, 0, 5, 6, 2, 5, 6, 0, 6, 0, 2, 5, 1,
       9, 7, 6, 3, 8, 2, 1, 1, 3, 4, 9, 8, 2, 7, 5, 0, 9, 4, 3, 2, 1, 4,
       7, 6, 0, 5, 7, 8, 3, 3, 2, 2, 3, 0, 9, 6, 1, 6, 4, 4, 6, 3, 2, 9,
       2, 8, 6, 7, 7, 5, 2, 3, 7, 9, 2, 8, 9, 0, 7, 3, 6, 9, 9, 9, 2, 6,
       5, 9, 7, 4, 2, 2, 4, 5, 1, 8, 3, 4, 6, 8, 1, 5, 4, 0, 3, 3, 5, 1,
       9, 1, 0, 9, 4, 3, 4, 8, 1, 2, 0, 5, 2, 5, 7,

# Get the errorrate

In [0]:
errors = 0
# compares the two arrays and is looking for matches of the values? Right = true / Wrong = false
error_rate_matrix = (test_labels_sample == knn_result)
for b in error_rate_matrix:
    if b == False:
        errors += 1

In [24]:
# Calculation of the error rate
_rate = (errors / size_test_sample) * 100. 
print("Error rate is: " +str(_rate) + " %")

Error rate is: 3.8 %
