<a href="https://colab.research.google.com/github/oliveralbrecht94/ATDIT2/blob/master/Task%20B.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Import of needed classes**

In [0]:
import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.manifold import TSNE
from scipy import stats
import scipy.spatial.distance


# Load MNIST DATASET

In [0]:
# load MNIST in mnistdataset
mnistdataset = tf.keras.datasets.mnist.load_data()[0]
# load first dimension (digits/images) in digitsand second dimension (labels) in labels
digits, labels = mnistdataset [0], mnistdataset [1]

In [0]:
# load MNIST in testdataset
testdataset = tf.keras.datasets.mnist.load_data()[1]
# load first dimension (digits) in test_digits and second dimension (labels) in test_labels
test_digits, test_labels = testdataset[0], testdataset[1]

# Preparing Dataset

In [0]:
# save amount of digits (from digits) in n_digits
n_digits = digits.shape[0] 
# save amount of digitis (from test_digits) in n_test
n_test = test_digits.shape[0] 

In [0]:
# calculation of full dimension of each image 28*28
amount_pixels = digits.shape[1] * digits.shape[2]

In [0]:
# Transform to 1D vector from each matrix with the pixels of an image in order to calculate distances.
digits = digits.reshape([n_digits, amount_pixels])
test_digits = test_digits.reshape([n_test, amount_pixels])

In [91]:
# see the result
digits.shape

(60000, 784)

In [0]:
# setting an index of 50.0000 between 0 and n_digits (60.000) 
index = np.random.randint(n_digits, size = 50000) 
# set up of samples 
digits_sample = digits[index]
labels_sample = labels[index]

In [0]:
# how much data should be consider? Size = 1000 -> 1000 numbers of the vector // it is faster!
size_test_sample = 1000 
index = np.random.randint(n_test, size = size_test_sample)
test_digits_sample = test_digits[index]
test_labels_sample = test_labels[index]

# Calculating Distances

In [0]:
# setting up the k value 
# k = 2 
k = 4
# k = 8 
# calculating the distance between each vector in dependency of k and save it in an arra
distances = scipy.spatial.distance.cdist(digits_sample, test_digits_sample, metric='euclid')
# calculates the next k points around the vector
index_nearest = np.argpartition(distances, k, axis = 0)[:k] 


In [95]:
# saves the neighbors of the vector in dependency of k
knn_neighbors = labels_sample[index_nearest] 
# show the neighbors
print(knn_neighbors)

[[7 6 6 ... 7 2 2]
 [7 6 6 ... 7 2 2]
 [7 6 6 ... 7 2 2]
 [7 6 6 ... 7 2 2]]


In [96]:
# is looking for the most frequent value in the array/vector
knn_result = stats.mode(knn_neighbors)[0]
knn_result = knn_result[0]
# shows the most frequent value
knn_result

array([7, 6, 6, 5, 2, 3, 8, 4, 0, 9, 5, 1, 2, 8, 7, 2, 7, 9, 9, 8, 1, 3,
       9, 9, 0, 5, 0, 8, 1, 0, 2, 5, 4, 0, 8, 4, 5, 7, 6, 8, 4, 3, 7, 7,
       0, 8, 3, 4, 0, 3, 5, 6, 5, 6, 1, 3, 0, 6, 1, 7, 9, 0, 8, 6, 8, 7,
       2, 4, 4, 3, 2, 0, 6, 1, 0, 2, 7, 2, 1, 6, 0, 0, 6, 7, 4, 4, 1, 3,
       7, 8, 3, 1, 7, 6, 7, 3, 0, 7, 0, 7, 5, 9, 2, 0, 4, 0, 4, 0, 4, 0,
       4, 9, 7, 4, 1, 0, 4, 2, 4, 7, 6, 2, 9, 8, 7, 7, 1, 2, 3, 4, 5, 0,
       7, 3, 1, 2, 5, 7, 0, 4, 2, 6, 7, 3, 6, 8, 8, 8, 7, 4, 4, 8, 2, 3,
       8, 8, 1, 7, 1, 0, 1, 7, 2, 3, 1, 7, 9, 3, 9, 4, 5, 0, 0, 1, 0, 5,
       3, 7, 1, 6, 9, 3, 8, 7, 6, 1, 0, 1, 2, 6, 0, 5, 6, 9, 9, 6, 8, 8,
       4, 0, 5, 5, 5, 3, 7, 7, 7, 7, 2, 7, 2, 6, 2, 7, 8, 6, 1, 4, 1, 3,
       5, 0, 8, 5, 0, 6, 1, 3, 8, 0, 7, 5, 3, 1, 0, 3, 5, 6, 3, 6, 2, 6,
       1, 7, 6, 7, 4, 3, 0, 7, 4, 0, 6, 9, 7, 4, 9, 7, 7, 3, 7, 4, 0, 7,
       2, 6, 0, 4, 5, 5, 1, 3, 1, 1, 2, 9, 8, 6, 5, 1, 5, 9, 2, 6, 3, 2,
       0, 0, 2, 5, 6, 2, 0, 0, 1, 9, 5, 2, 0, 9, 4,

# Get the global errorrate

In [0]:
errors = 0
# compares the two arrays and is looking for matches of the values? Right = true / Wrong = false
error_rate_matrix = (test_labels_sample == knn_result)
for b in error_rate_matrix:
    if b == False:
        errors += 1



In [98]:
np.unique(test_labels_sample, return_counts=True)

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=uint8),
 array([109, 117,  96,  94,  86,  91, 101, 123,  98,  85]))

In [99]:
# Calculation of the error rate
_rate = (errors / size_test_sample) * 100. 
print("Global error rate is: " +str(_rate) + " %")

Global error rate is: 3.6999999999999997 %


# Get the individual errorrate

In [0]:
indi_error ={0:0,1:0,2:0,3:0,4:0,5:0,6:0,7:0,8:0,9:0}
total = {0:0,1:0,2:0,3:0,4:0,5:0,6:0,7:0,8:0,9:0}
for i in range(len(test_labels_sample)):
  if test_labels_sample[i]!= knn_result[i]:
    # speicher das die zahl falsch war
    indi_error[test_labels_sample[i]] +=1
    total[test_labels_sample[i]] +=1
  else:
    # speicher das die zahl richtig war
    total[test_labels_sample[i]] +=1

In [101]:
total

{0: 109, 1: 117, 2: 96, 3: 94, 4: 86, 5: 91, 6: 101, 7: 123, 8: 98, 9: 85}

In [102]:
indi_error

{0: 0, 1: 0, 2: 3, 3: 3, 4: 3, 5: 4, 6: 2, 7: 3, 8: 10, 9: 9}

In [105]:
errorrate = {}
for j in range(0,10):
  errorrate[j] = (indi_error[j]/total[j]) * 100
  print(errorrate[j])


0.0
0.0
3.125
3.1914893617021276
3.488372093023256
4.395604395604396
1.9801980198019802
2.4390243902439024
10.204081632653061
10.588235294117647


In [106]:
for i in range(len(errorrate)):
  print("Error rate for number "+ str(i) +" is "+ str(errorrate[i]))

Error rate for number 0 is 0.0
Error rate for number 1 is 0.0
Error rate for number 2 is 3.125
Error rate for number 3 is 3.1914893617021276
Error rate for number 4 is 3.488372093023256
Error rate for number 5 is 4.395604395604396
Error rate for number 6 is 1.9801980198019802
Error rate for number 7 is 2.4390243902439024
Error rate for number 8 is 10.204081632653061
Error rate for number 9 is 10.588235294117647
